source 'https://rubygems.org'
gem 'grape'
gem 'rake'
group :development, :test do
	gem 'rspec'
	gem 'rspec-its'
	gem 'byebug'
	gem 'rack-test'
	gem 'simplecov', require: false
	gem 'rubocop'
    gem 'cane'
end
